# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Library
on: ["push", "pull_request"]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        pnpm: [6.30.0]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v1
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
    - run: pnpm install
    - run: make test-coverage
      # pnpm test
      # pnpm coverage
    # - run: make test-coverage
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        pnpm: [6.30.0]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: pnpm install
    - run: pnpm build --if-present
