name: Build and Test Library
on: ["push", "pull_request"]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.x]
        pnpm: [6.30.0]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v1
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
    - run: pnpm install
    - run: pnpm build
    - run: pnpm test
    - run: pnpm coverage
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}